# Install combat 
source("https://bioconductor.org/biocLite.R")
biocLite("sva")

# installing packages for test data
install.packages(c("devtools"))
source("http://www.bioconductor.org/biocLite.R")
biocLite(c("Biobase","sva","bladderbatch","snpStats"))

# Link to tutorial:
http://jtleek.com/genstats/inst/doc/02_13_batch-effects.html


# load combat
library("sva")
require(data.table)


# load in csv files (generated by python script) (takes a while)
meth_data <- fread('RAmeth_matrix_linesremoved.csv')
# convert dataframe to matrix (required by combat) removing col names and row names
meth_data_matrix <- data.matrix(meth_data[-1,-1], rownames.force = NA)


batchdata <- read.csv("samplebatches.csv")
# transpose dataframe
batchdata <- t(batchdata)

# select just batch values for the batch variable
batch <- batchdata[,1]


# try combat
combat_data <- ComBat(dat=meth_data_matrix, batch=batch, mod=NULL, par.prior=True, 
					 prior.plots = FALSE, mean.only = FALSE, ref.batch = NULL,
					 BPPARAM = bpparam("SerialParam"))