#install HIRE
library("devtools")
install_github("XiangyuLuo/HIREewas")

# load HIRE
library("HIREewas")
require(data.table)

# load in csv files (generated by python script) (takes a while)
meth_data <- fread('RAmeth_matrix_linesremoved.csv')

# load samples
samples <- fread('samplesheet_colremoved.csv') 

# test
samples <- data.matrix(read.csv('samplesheet_colremoved.csv', row.names = 1))
meth_data <- data.matrix(read.csv('RAmeth_matrix_linesremoved.csv', row.names = 1))


#test HIRE
ret_list <- HIRE(meth_data, samples, num_celltype=6)