#install HIRE
library("devtools")
install_github("XiangyuLuo/HIREewas")

# load HIRE
library("HIREewas")

# load in csv files (generated by python script) (takes a while)
meth_data <- fread('RAmeth_matrix_linesremoved.csv')

# load samples
samples <- fread('samplesheet_colremoved.csv')

#test HIRE
ret_list <- HIRE(meth_data, samples, num_celltype=6)